[package]
name = "pytorch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
tch = "0.15.0"
tokio = { version = "1.37.0", features = ["full"] }
